SeaWave/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_service.urls')),
    path('', include('post_service.urls')),
    path('', include('ui_service.urls')),
    # path('', include('chat_service.urls')),
    # Add other app URLs as needed
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ui_service/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('posts/create/', views.create_post, name='create-post'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('posts/<int:pk>/edit/', views.edit_post, name='edit-post'),
    path('posts/<int:pk>/delete/', views.delete_post, name='delete-post'),
    path('posts/<int:pk>/comments/', views.create_comment, name='create-comment'),
    path('comments/<int:pk>/edit/', views.edit_comment, name='edit-comment'),
    path('comments/<int:pk>/delete/', views.delete_comment, name='delete-comment'),
    path('comments/<int:pk>/', views.CommentDetailView.as_view(), name='comment-detail'),
    path('posts/<int:pk>/like/', views.like_post, name='like-post'),
    path('comments/<int:pk>/like/', views.like_comment, name='like-comment'),
    path('users/<str:username>/', views.user_detail, name='user-profile'),
    path('users/<str:username>/posts/', views.UserPostList.as_view(), name='user-post-list'),
    path('users/follow/<str:username>/', views.follow_unfollow_user, name='follow-unfollow-user'),
    path('users/<str:username>/update/', views.update_profile, name='update-profile'),
    path('posts/<int:post_id>/share/', views.share_post, name='share-post'),
    path('posts/<int:post_id>/get_comments/', views.get_comments, name='get-comments'),
]

#
#  urlpatterns = [
#     path('', views.home, name='home'),
#     path('posts/', views.PostList.as_view(), name='post-list'),
#     path('posts/create/', views.create_post, name='create-post'),
#     path('posts/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
#     path('posts/<int:pk>/edit/', views.edit_post, name='edit-post'),
#     path('posts/<int:pk>/delete/', views.delete_post, name='delete-post'),
#     path('posts/<int:pk>/comments/', views.create_comment, name='create-comment'),
#     path('comments/<int:pk>/edit/', views.edit_comment, name='edit-comment'),
#     path('comments/<int:pk>/delete/', views.delete_comment, name='delete-comment'),
#     path('api/posts/<int:pk>/like/', views.like_post, name='like-post'),
#     path('comments/<int:pk>/like/', views.like_comment, name='like-comment'),
#     path('users/<str:username>/', views.UserProfileView.as_view(), name='user-profile'),
#     path('users/<str:username>/posts/', views.UserPostList.as_view(), name='user-post-list'),
#     path('register/', views.register, name='register'),
#     path('login/', views.user_login, name='login'),
#     path('logout/', views.user_logout, name='logout'),
# ]
#     # API URLs
#     # path('api/posts/', views.PostViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-post-list'),
#     # path('api/posts/<int:pk>/', views.PostViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-post-detail'),
#     # path('api/comments/', views.CommentViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-comment-list'),
#     # path('api/comments/<int:pk>/', views.CommentViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-comment-detail'),
#     # path('api/post-likes/', views.PostLikeViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-post-like-list'),
#     # path('api/post-likes/<int:pk>/', views.PostLikeViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-post-like-detail'),
#     # path('api/comment-likes/', views.CommentLikeViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-comment-like-list'),
#     # path('api/comment-likes/<int:pk>/', views.CommentLikeViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-comment-like-detail'),
#     # path('api/user-profiles/', views.UserProfileViewSet.as_view({'get': 'list', 'post': 'create'}), name='api-user-profile-list'),
#     # path('api/user-profiles/<int:pk>/', views.UserProfileViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'}), name='api-user-profile-detail'),
# ]

post_service/models.py
# post_service/models.py

from django.db import models

class Post(models.Model):
    author = models.ForeignKey('user_service.CustomUser', on_delete=models.CASCADE)
    text = models.TextField()
    media = models.ImageField( null=True, blank=True)
    media_url = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_count = models.IntegerField(default=0)
    share_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)

class PostLike(models.Model):
    user = models.ForeignKey('user_service.CustomUser', on_delete=models.CASCADE, related_name='postLikes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postLikes')
    created_at = models.DateTimeField(auto_now_add=True)
    
class Comment(models.Model):
    text = models.TextField()
    user = models.ForeignKey('user_service.CustomUser', on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True) 
    like_count = models.IntegerField(default=0)  

class CommentLike(models.Model):
    user = models.ForeignKey('user_service.CustomUser', on_delete=models.CASCADE, related_name='commentLikes')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='commentLikes')
    created_at = models.DateTimeField(auto_now_add=True)

ui_service/forms.py
from django import forms
from user_service.models import CustomUser
from django.contrib.auth.forms import UserCreationForm
from post_service.models import Post, Comment

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegistrationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['id', 'username', 'email', 'gender', 'birthday']

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

class PostForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    class Meta:
        model = Post
        fields = ['text']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['avatar', 'cover_photo', 'bio']

ui_service/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseForbidden, JsonResponse

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, RegistrationForm, PostForm
from django.contrib import messages
import firebase_admin
from firebase_admin import storage, credentials
from .forms import PostForm, CommentForm, UserProfileForm
from post_service.models import Post, Comment, PostLike, CommentLike
from post_service.serializers import PostSerializer, CommentSerializer, PostLikeSerializer, CommentLikeSerializer
from user_service.models import CustomUser
from rest_framework import viewsets
from django.views import View
from django.views.generic.edit import FormMixin
from django.views.generic import ListView
from django.urls import reverse_lazy
from follow_service.models import Follower

cred = credentials.Certificate('firebase_credentials.json')
try:
    firebase_admin.initialize_app(cred, name='SeaWave')
except ValueError as e:
    messages.error("Error initializing Firebase app: %s", e)

# Firebase Storage bucket name
BUCKET_NAME = 'seawave-d58e4.appspot.com'

class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class PostLikeViewSet(viewsets.ModelViewSet):
    queryset = PostLike.objects.all()
    serializer_class = PostLikeSerializer


class CommentLikeViewSet(viewsets.ModelViewSet):
    queryset = CommentLike.objects.all()
    serializer_class = CommentLikeSerializer

class UserPostList(View):
    def get(self, request, username):
        user = get_object_or_404(CustomUser, username=username)
        posts = Post.objects.filter(author=user)
        context = {'user': user, 'posts': posts}
        # return render(request, 'app_main/user_post_list.html', context)

class PostList(FormMixin, ListView):
    model = Post
    template_name = 'ui_service/home.html'
    context_object_name = 'posts'
    ordering = '-create_at'
    form_class = PostForm
    success_url = reverse_lazy('home')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class UserProfileView(View):
    def get(self, request, username):
        user = CustomUser.objects.get(username=username)
        posts = Post.objects.filter(author=user)
        follower_count = Follower.objects.filter(user=user).count()
        is_following = Follower.objects.filter(user=user, follower=request.user).exists()
        
        context = {
            'user': user,
            'follower_count': follower_count,
            'is_following': is_following,
            'posts' : posts
        }
        return render(request, 'ui_service/user_profile.html', context)

@login_required
def user_detail(request, username):
    user = CustomUser.objects.get(username=username)
    posts = Post.objects.filter(author=user).order_by('-created_at')
    follower_count = user.followers.count()
    is_following = user.followers.filter(follower=request.user).exists()

    update_profile_form = UserProfileForm(instance=user)

    if request.method == 'POST':
        update_profile_form = UserProfileForm(request.POST, request.FILES, instance=user)
        if update_profile_form.is_valid():
            update_profile_form.save()
            return redirect('user-detail', username=username)

    context = {
            'user': user,
            'follower_count': follower_count,
            'is_following': is_following,
            'posts' : posts,
            'update_profile_form': update_profile_form
    }
    
    return render(request, 'ui_service/user_profile.html', context)


class PostDetailView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        comment_form = CommentForm()
        comments = post.comments.all() 
        return render(request, 'ui_service/post_detail.html', {'post': post, 'comment_form': comment_form, 'comments': comments})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('post-detail', pk=pk)

        comments = post.comments.all()
        return render(request, 'ui_service/post-post_detail.html', {'post': post, 'comment_form': comment_form, 'comments': comments})
    

class CommentDetailView(View):
    def get(self, request, pk):
        comment = get_object_or_404(Comment, pk=pk)
        text = comment.text
        return JsonResponse({'text': text})

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = RegistrationForm()
    return render(request, 'ui_service/register.html', {'form': form})    

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return render(request, 'ui_service/home.html', {'form': form})
            else:
                messages.error(request, 'Invalid username or password')  # Add an error message
    else:
        form = LoginForm()
    return render(request, 'ui_service/home.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('home')  

def update_media(post, file):
    if post.media_url:
        existing_file_name = post.media_url.split('/')[-1]
        blob = storage.bucket(BUCKET_NAME).blob('post_media/' + str(post.id) + '/' + existing_file_name)
        blob.delete()

    bucket = storage.bucket(BUCKET_NAME)
    blob = bucket.blob('post_media/' + str(post.id) + '/' + file.name)
    file.seek(0)  # Ensure the file is at the beginning
    blob.upload_from_file(file, content_type='image/jpeg')  # Set the content type to image/jpeg
    blob.make_public()
    post.media_url = blob.public_url
    post.save()

@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            print("AnhWasHere")
            print(post.id)

            if 'media' in request.FILES:
                media_file = request.FILES['media']
                try:
                    update_media(post, media_file)
                except Exception as e:
                    return JsonResponse({'success': False, 'error': str(e)})
                
                return redirect('home')
            
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = PostForm()

    return redirect('home')

@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            post = form.save(commit=False)
            post.save()
            if 'media' in request.FILES:
                media_file = request.FILES['media']
                try:
                    update_media(post, media_file)
                except Exception as e:
                    return JsonResponse({'success': False, 'error': str(e)})
            return redirect('post-detail', pk=pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'ui_service/edit_post.html', {'form': form, 'post': post})

@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.user == post.author or request.user.is_superuser:
        if request.method == 'POST':
            post.delete()
            return redirect('home')

        return render(request, 'ui_service/delete_post.html', {'post': post})

    return HttpResponseForbidden()

@login_required
def share_post(request, post_id):
    post = Post.objects.get(pk=post_id)

    post.share_count += 1
    post.save()

    return JsonResponse({'share_count': post.share_count})

@login_required
def get_comments(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(post=post).order_by('created_at')
    
    comments_data = []
    for comment in comments:
        comments_data.append({
            'id': comment.id,
            'text': comment.text,
            'like_count': comment.like_count, 
            'user' : comment.user.username,
            'avatar_url' : comment.user.avatar_url,
            'created_at' : comment.created_at,
            'is_authenticated': request.user.is_authenticated,
            'is_comment_author': comment.user.username == request.user.username,
        })

    return JsonResponse(comments_data, safe=False)

@login_required
def create_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.user_id = request.user.id
            comment.save()
            post.comment_count += 1

ui_service/templates/ui_service/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SeaWave</title>
    <link rel="stylesheet" href="{% static 'ui_service/css/style.css' %}">
</head>
<body>
    <header>
        <h1>SeaWave</h1>
        {% if user.is_authenticated %}
            <h2>Welcome, {{ user.username }}!</h2>
            

            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>

        {% endif %}
    </header>

    <main>
        {% block content %}
        <!-- The child templates will override this block with their specific content -->
        {% endblock %}
    </main>

    <footer>
        &copy; 2023 My App. All rights reserved.
    </footer>
    <script src="{% static 'ui_service/js/script.js' %}"></script>

</body>
</html>

ui_service/templates/ui_service/comment_list.html
<!-- comment_list.html -->
{% extends 'ui_service/base.html' %}
{% for comment in comments %}
  <div class="comment">
    <p>{{ comment.content }}</p>
    <p>Author: {{ comment.author }}</p>
    <p>Timestamp: {{ comment.created_at }}</p>
  </div>
{% endfor %}

ui_service/templates/ui_service/delete_comment.html
{% extends 'ui_service/base.html' %}

{% block content %}
  <h2>Delete Comment</h2>
  <p>Are you sure you want to delete this comment?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
{% endblock %}

ui_service/templates/ui_service/delete_post.html
<!-- ui_service/templates/ui_service/delete_post.html -->
{% extends 'ui_service/base.html' %}

{% block content %}
  <h2>Delete Post</h2>
  <p>Are you sure you want to delete the following post?</p>
  <div class="post-container">
    <div class="post-header">
      <div>
        <p class="post-author">{{ post.author }}</p>
        <p class="post-timestamp">{{ post.created_at }}</p>
      </div>
    </div>
    <div class="post-content">
      <p>{{ post.text }}</p>
      {% if post.media_url %}
        <img class="post-image" src="{{ post.media_url }}" alt="Post Media">
      {% endif %}
    </div>
  </div>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm Delete</button>
  </form>
  <a href="{% url 'home' %}">Cancel</a>
{% endblock %}

ui_service/templates/ui_service/edit_post.html
{% extends 'ui_service/base.html' %}
{% block content %}
    {% if user.is_authenticated %}
    <div class="container">
        <div class="post-creation-container">
            <form class="create-post-form" method="post" action="{% url 'edit-post' post.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                    <p>
                        <label for="post_text">Edit Post:</label>
                        <textarea id="post_text" name="text" id="id_text" required> {{ post.text }}</textarea>
                    </p>
                    {% if post.media_url %}
                        <img class="post-image" src="{{ post.media_url }}" alt="Post Media">
                    {% endif %}
                    <p>
                        <label for="id_media">Media:</label>
                        <input type="file" name="media" id="id_media">
                    </p>
                    <div id="media-preview"></div>
                    <input type="submit" value="Edit Post">
            </form>
        </div>
    </div>

    {% endif %}
{% endblock %}

ui_service/templates/ui_service/home.html
{% extends 'ui_service/base.html' %}

{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
        <div class="post-creation-container">
            <form class="create-post-form" method="post" action="{% url 'create-post' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    <label for="post_text">Create New Post:</label>
                    <textarea id="post_text" name="text" id="id_text" required></textarea>
                </p>
                <p>
                    <label for="id_media">Media:</label>
                    <input type="file" name="media" id="id_media">
                </p>
                <div id="media-preview"></div>
                <input type="submit" value="Create Post">
            </form>
        </div>
        {% endif %}

        {% for post in posts %}
            <div class="post-container">
                <div class="post-header">
                        <a href="{% url 'user-profile' post.author.username %}">
                            <img class="post-avatar" src="{{ post.author.avatar_url }}" alt="Author Avatar">
                        </a>
                        <div>
                            <a href="{% url 'user-profile' post.author.username %}" style="text-decoration: none;">
                                <p class="post-author">{{ post.author }}</p>
                            </a>
                            <p class="post-timestamp">{{ post.created_at }}</p>
                        </div>     
                    <hr>
                    {% if user.is_authenticated and post.author == user %}
                        <div class="post-actions-dropdown">
                            <button class="post-actions-btn">&#x2026;</button>
                            <div class="post-actions-content">
                                <a href="{% url 'edit-post' post.id %}" class="post-action">Edit</a>
                                <a href="{% url 'delete-post' post.id %}" class="post-action">Delete</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <hr>
                <div class="post-content">
                    <a href="{% url 'post-detail' post.pk %}" class="post-link">{{ post.text }}
                        <hr>
                        {% if post.media_url %}
                            <img class="post-image" src="{{ post.media_url }}" alt="Post Media">
                        {% endif %}
                    </a>
                </div>
                <hr>
                <div class="count-container">
                    <p class="post-like-count">Likes: <span id="like-count-{{ post.pk }}">{{ post.like_count }}</span></p>
                    <p class="post-comment-count">Comments: <span id="comment-count-{{ post.pk }}">{{ post.comment_count }}</span></p>
                    <p class="post-share-count">Shares: <span id="share-count-{{ post.pk }}">{{ post.share_count }}</span></p>
                </div>
                <hr>
                <div class="post-actions">
                    <button class="like-button" data-post-id="{{ post.pk }}">Like</button>
                    <button class="comment-button" data-post-id="{{ post.pk }}">Comment</button>
                    <button class="share-button" data-post-id="{{ post.pk }}">Share</button>
                </div>
                <div class="comment-section" id="comment-section-{{ post.pk }}">
                    <!-- Comments will be displayed here -->
                </div>

                <div class="create-comment-section" id="create-comment-section-{{ post.pk }}" style="display: none;">
                    <img class="comment-avatar" src="{{ user.avatar_url }}" alt="User Avatar">
                    <textarea id="create-comment-text-{{ post.pk }}" placeholder="Add your comment..." name="text" required></textarea>
                    <button class="create-comment-class" data-post-id="{{ post.pk }}" style="width: 20%;">Comment</button>
                </div>
            </div>
        {% endfor %}
    </div>

    <script>
        const csrfToken = "{{ csrf_token }}";
    </script>

    {% if not user.is_authenticated %}
    <div class="login-form">
        <h2>Login</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <button type="submit">Login</button>
        </form>
        <p></p>
        <p>Don't have an account? <a href="{% url 'register' %}">Sign up</a></p>
    </div>
    {% endif %}
{% endblock %}

ui_service/templates/ui_service/user_profile.html
{% extends 'ui_service/base.html' %}
{% block content %}
{% if user.is_authenticated %}
    <div class="photo-profile-container">
        <div class="cover-photo-container">
            {% if user.cover_photo %}
                <img class="cover-photo" src="{{ user.cover_photo.url }}" alt="{{ user.username }} Cover Photo">
            {% endif %}
            <div class="avatar-container">
                {% if user.avatar %}
                    <img class="avatar" src="{{ user.avatar.url }}" alt="{{ user.username }} Avatar">
                {% endif %}
            </div>
        </div>

        <div class="user-info">
            <div class="user-name">{{ user.username }}</div>
            <div class="user-email">Email: {{ user.email }}</div>
            <div class="user-joined">Joined: {{ user.created_at }}</div>
            <div class="user-followers">Followers: {{ follower_count }}</div>
            <div class="user-bio">Bio: {{ user.bio }}</div>
        </div>
    </div>
    {% if user != request.user %}
        {% if is_following %}
            <form method="post" action="{% url 'follow-unfollow-user' user.username %}">
                {% csrf_token %}
                <button class="follow-button" type="submit">Unfollow</button>
            </form>
        {% else %}
            <form method="post" action="{% url 'follow-unfollow-user' user.username %}">
                {% csrf_token %}
                <button class="follow-button" type="submit">Follow</button>
            </form>
        {% endif %}
    {% endif %}

    <div class="container">
        {% if user.is_authenticated %}
        <div class="post-creation-container">
            <form class="create-post-form" method="post" action="{% url 'create-post' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <p>
                    <label for="post_text">Create New Post:</label>
                    <textarea id="post_text" name="text" id="id_text" required></textarea>
                </p>
                <p>
                    <label for="id_media">Media:</label>
                    <input type="file" name="media" id="id_media">
                </p>
                <div id="media-preview"></div>
                <input type="submit" value="Create Post">
            </form>
        </div>
        {% endif %}

        {% for post in posts %}
            <div class="post-container">
                <div class="post-header">
                        <a href="{% url 'user-profile' post.author.username %}">
                            <img class="post-avatar" src="{{ user.avatar.url }}" alt="Author Avatar">
                        </a>
                        <div>
                            <a href="{% url 'user-profile' post.author.username %}" style="text-decoration: none;">
                                <p class="post-author">{{ post.author }}</p>
                            </a>
                            <p class="post-timestamp">{{ post.created_at }}</p>
                        </div>     
                    <hr>
                    {% if user.is_authenticated and post.author == user %}
                        <div class="post-actions-dropdown">
                            <button class="post-actions-btn">&#x2026;</button>
                            <div class="post-actions-content">
                                <a href="{% url 'edit-post' post.id %}" class="post-action">Edit</a>
                                <a href="{% url 'delete-post' post.id %}" class="post-action">Delete</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <hr>
                <div class="post-content">
                    <a href="{% url 'post-detail' post.pk %}" class="post-link">{{ post.text }}
                        <hr>
                        {% if post.media_url %}
                            <img class="post-image" src="{{ post.media_url }}" alt="Post Media">
                        {% endif %}
                    </a>
                </div>
                <hr>
                <div class="count-container">
                    <p class="post-like-count">Likes: <span id="like-count-{{ post.pk }}">{{ post.like_count }}</span></p>
                    <p class="post-comment-count">Comments: <span id="comment-count-{{ post.pk }}">{{ post.comment_count }}</span></p>
                    <p class="post-share-count">Shares: <span id="share-count-{{ post.pk }}">{{ post.share_count }}</span></p>
                </div>
                <hr>
                <div class="post-actions">
                    <button class="like-button" data-post-id="{{ post.pk }}">Like</button>
                    <button class="comment-button" data-post-id="{{ post.pk }}">Comment</button>
                    <button class="share-button" data-post-id="{{ post.pk }}">Share</button>
                </div>
                <div class="comment-section" id="comment-section-{{ post.pk }}">
                    <!-- Comments will be displayed here -->
                </div>

                <div class="create-comment-section" id="create-comment-section-{{ post.pk }}" style="display: none;">
                    <img class="comment-avatar" src="{{ user.avatar_url }}" alt="User Avatar">
                    <textarea id="create-comment-text-{{ post.pk }}" placeholder="Add your comment..." name="text" required></textarea>
                    <button class="create-comment-class" data-post-id="{{ post.pk }}" style="width: 20%;">Comment</button>
                </div>
            </div>
        {% endfor %}
    </div>

    </div>
    <script>
        const csrfToken = "{{ csrf_token }}";
    </script>
    {% endif %}
{% endblock %}